const RUSSIAN = {
  Sunday: "Воскресенье",
  Monday: "Понедельник",
  Tuesday: "Вторник",
  Wednesday: "Среда",
  Thursday: "Четверг",
  Friday: "Пятница",
  Saturday: "Суббота",
  searchButton: "ПОИСК",
  feelsLikeLabel: "ОЩУЩАЕТСЯ КАК",
  windLabel: "СКОРОСТЬ ВЕТРА",
  humidityLabel: "ВЛАЖНОСТЬ",
  latitudeLabel: "ШИРОТА",
  longitudeLabel: "ДОЛГОТА",
  Sun: "Вс",
  Mon: "Пн",
  Tue: "Вт",
  Wed: "Ср",
  Thu: "Чт",
  Fri: "Пт",
  Sat: "Сб",
  January: "Января",
  February: "Февраля",
  March: "Марта",
  April: "Апреля",
  May: "Мая",
  June: "Июня",
  July: "Июля",
  August: "Августа",
  September: "Сентября",
  October: "Октября",
  November: "Ноября",
  December: "Декабря",
  searchPlaceholder: "Поиск города",
};

const ENGLISH = {
  Sunday: "Sunday",
  Monday: "Monday",
  Tuesday: "Tuesday",
  Wednesday: "Wednesday",
  Thursday: "Thursday",
  Friday: "Friday",
  Saturday: "Saturday",
  searchButton: "SEARCH",
  feelsLikeLabel: "FEELS LIKE",
  windLabel: "WIND",
  humidityLabel: "HUMIDITY",
  latitudeLabel: "LATITUDE",
  longitudeLabel: "LONGITUDE",
  Sun: "Sun",
  Mon: "Mon",
  Tue: "Tue",
  Wed: "Wed",
  Thu: "Thu",
  Fri: "Fri",
  Sat: "Sat",
  January: "January",
  February: "February",
  March: "March",
  April: "April",
  May: "May",
  June: "June",
  July: "July",
  August: "August",
  September: "September",
  October: "October",
  November: "November",
  December: "December",
  searchPlaceholder: "Search city",
};

const dictionaries = {
  en: ENGLISH,
  ru: RUSSIAN,
};

const getDictionary = (langCode) => {
  return dictionaries[langCode];
};
